# Shared path helpers used by the CT and RNA workflows.
# Keeping paths here avoids small naming drift between rule outputs and inputs.

# Raw FASTQs are discovered recursively below rawData_dir/<sample>/.
def raw_fastq_glob(sample, number, lane, read, suffix, ext):
  return raw_dir + '{sample}/**/{sample}_{number}_{lane}_{read}_{suffix}.{ext}'.format(
    sample=sample,
    number=number,
    lane=lane,
    read=read,
    suffix=suffix,
    ext=ext
  )

# QC FASTQs are intermediate reads generated by the shared spatial demux filters.
def qc_fastq(sample, number, lane, read, step, suffix, ext):
  return proc_dir + '{sample}/tmp_data/qc_raw_data/{sample}_{number}_{lane}_{read}_{step}_{suffix}.{ext}'.format(
    sample=sample,
    number=number,
    lane=lane,
    read=read,
    step=step,
    suffix=suffix,
    ext=ext
  )

# QC done files are gatekeepers: they are touched only after the rule completes.
def qc_done(sample, number, lane, suffix, ext, step):
  return sample_lane_done(sample, number, lane, suffix, ext, step)

# tmp_fastq contains post-BC-process FASTQs that are ready for debarcode/cellranger.
def tmp_fastq(sample, number, lane, read, suffix, ext):
  return proc_dir + '{sample}/tmp_data/{sample}_{number}_{lane}_{read}_{suffix}.{ext}'.format(
    sample=sample,
    number=number,
    lane=lane,
    read=read,
    suffix=suffix,
    ext=ext
  )

# tmp done files gatekeep tmp FASTQ-producing rules.
def tmp_done(sample, number, lane, suffix, ext, step):
  return sample_lane_done(sample, number, lane, suffix, ext, step)

# One CT sample can contain multiple modalities/barcodes, each with its own folder.
def ct_modality_dir(sample, modality, barcode):
  return proc_dir + '{sample}/{modality}_{barcode}'.format(
    sample=sample,
    modality=modality,
    barcode=barcode
  )

# FASTQs created by debarcode.py and consumed by Cell Ranger ATAC.
def ct_debarcoded_fastq(sample, modality, barcode, number, lane, read, suffix, ext):
  return ct_modality_dir(sample, modality, barcode) + '/fastq/barcode_{barcode}/{sample}_{number}_{lane}_{read}_{suffix}.{ext}'.format(
    sample=sample,
    barcode=barcode,
    number=number,
    lane=lane,
    read=read,
    suffix=suffix,
    ext=ext
  )

# Cell Ranger output files for CT.
def ct_cellranger_out(sample, modality, barcode, filename):
  return ct_modality_dir(sample, modality, barcode) + '/cellranger/outs/{filename}'.format(
    filename=filename
  )

# Cell Ranger output files for RNA.
def rna_cellranger_out(sample, filename):
  return proc_dir + '{sample}/cellranger/outs/{filename}'.format(
    sample=sample,
    filename=filename
  )

# CT bigWig output files.
def ct_bigwig(sample, modality, barcode, filename):
  return ct_modality_dir(sample, modality, barcode) + '/bigwig/{filename}'.format(
    filename=filename
  )

# CT MACS broadPeak output file for one modality.
def ct_macs_broad_peak(sample, modality, barcode):
  return ct_modality_dir(sample, modality, barcode) + '/peaks/macs_broad/{modality}_peaks.broadPeak'.format(
    modality=modality
  )

# Barcode metrics generated from Cell Ranger BAMs.
def ct_barcode_metrics(sample, modality, barcode, filename):
  return ct_modality_dir(sample, modality, barcode) + '/barcode_metrics/{filename}'.format(
    filename=filename
  )

# Base matrix folder for all fragtk matrices of one CT modality.
def ct_matrix_base(sample, modality, barcode):
  return ct_modality_dir(sample, modality, barcode) + '/matrix'

# Matrix directory outputs are Snakemake directory() outputs.
def ct_matrix_dir(sample, modality, barcode, matrix_name):
  return ct_matrix_base(sample, modality, barcode) + '/{matrix_name}/'.format(
    matrix_name=matrix_name
  )

# Files inside a matrix directory, such as BED/GTF helper files.
def ct_matrix_file(sample, modality, barcode, matrix_name, filename):
  return ct_matrix_dir(sample, modality, barcode, matrix_name) + filename

# fragtk writes to hidden temp matrix dirs first, then rules move them into place.
def matrix_tmp_dir(sample, modality, barcode, matrix_name):
  return ct_matrix_base(sample, modality, barcode) + '/.{matrix_name}.tmp/'.format(
    matrix_name=matrix_name
  )

# Active Cell Ranger whitelist path. Rules temporarily replace this file.
def cellranger_barcodes_path():
  return config['general']['cellranger']['barcodes_path'] + config['general']['cellranger']['barcodes_file']

# Workflow-local backup of the original Cell Ranger whitelist.
def cellranger_barcodes_backup():
  backup_name = config['general']['cellranger']['barcodes_file'].replace('/', '_')
  return proc_dir + '.done/cellranger_{backup_name}.original'.format(
    backup_name=backup_name
  )

# Done-file helpers. These are dependency gatekeepers, not biological outputs.
def sample_done(sample, name):
  return proc_dir + '{sample}/.done/{name}.done'.format(
    sample=sample,
    name=name
  )

def sample_lane_done(sample, number, lane, suffix, ext, name):
  return proc_dir + '{sample}/.done/{name}_{number}_{lane}_{suffix}.{ext}.done'.format(
    sample=sample,
    number=number,
    lane=lane,
    suffix=suffix,
    ext=ext,
    name=name
  )

def modality_done(sample, modality, barcode, name):
  return proc_dir + '{sample}/{modality}_{barcode}/.done/{name}.done'.format(
    sample=sample,
    modality=modality,
    barcode=barcode,
    name=name
  )

def modality_lane_done(sample, modality, barcode, number, lane, suffix, ext, name):
  return proc_dir + '{sample}/{modality}_{barcode}/.done/{name}_{number}_{lane}_{suffix}.{ext}.done'.format(
    sample=sample,
    modality=modality,
    barcode=barcode,
    number=number,
    lane=lane,
    suffix=suffix,
    ext=ext,
    name=name
  )

def global_done(name):
  return proc_dir + '.done/{name}.done'.format(
    name=name
  )

# Log helpers mirror the done-file layout so each rule has a predictable log file.
def global_log(name):
  return proc_dir + 'logs/{name}.log'.format(
    name=name
  )

def sample_log(sample, name):
  return proc_dir + '{sample}/logs/{name}.log'.format(
    sample=sample,
    name=name
  )

def sample_lane_log(sample, number, lane, suffix, ext, name):
  return proc_dir + '{sample}/logs/{name}_{number}_{lane}_{suffix}.{ext}.log'.format(
    sample=sample,
    number=number,
    lane=lane,
    suffix=suffix,
    ext=ext,
    name=name
  )

def modality_log(sample, modality, barcode, name):
  return ct_modality_dir(sample, modality, barcode) + '/logs/{name}.log'.format(
    name=name
  )

def modality_lane_log(sample, modality, barcode, number, lane, suffix, ext, name):
  return ct_modality_dir(sample, modality, barcode) + '/logs/{name}_{number}_{lane}_{suffix}.{ext}.log'.format(
    number=number,
    lane=lane,
    suffix=suffix,
    ext=ext,
    name=name
  )
